FROM python:3.11

ENV DBT_PROFILES_DIR=/pipeline/ \ 
    DUCKDB_PATH=/duckdb_warehouse/job_ads.duckdb

WORKDIR /pipeline/orchestration

COPY dlt_code/ /pipeline/dlt_code/
COPY dbt_code/ /pipeline/dbt_code/
COPY orchestration/ /pipeline/orchestration/

RUN pip install dagster dagster-dbt dagster-dlt dagster-webserver dbt-core dbt-duckdb dlt duckdb

CMD ["dagster", "dev", "-f", "definitions.py", "-h", "0.0.0.0", "-p", "3000"]
