FROM python:3.11-slim

ENV DUCKDB_PATH=/duckdb_warehouse/job_ads.duckdb

WORKDIR /app/dashboard

COPY dashboard/ /app/dashboard/

RUN pip install streamlit duckdb pandas python-dotenv

CMD ["streamlit", "run", "dashboard_main.py", "--server.port=8501", "--server.address=0.0.0.0"]