FROM python:3.11

WORKDIR /pipeline/orchestration

COPY dlt_code/ /pipeline/dlt_code/
COPY dbt_code/ /pipeline/dbt_code/
COPY orchestration/ /pipeline/orchestration/

RUN pip install dagster dagster-dbt dagster-dlt dagster-webserver dbt-core dbt-duckdb dlt duckdb

EXPOSE 3000

CMD ["dagster", "dev", "-f", "definitions.py", "-h", "0.0.0.0", "-p", "3000"]
